# Tema Kanagawa Wave para Alacritty
[colors]
# Cores primárias
[colors.primary]
background = "#1f1f28"  # Fundo escuro suave
foreground = "#dcd7ba"  # Texto bege suave

# Cursor
[colors.cursor]
text = "#1f1f28"        # Cor do texto no cursor
cursor = "#dcd7ba"      # Cor do cursor

# Cores normais
[colors.normal]
black   = "#1f1f28"     # Preto suave (fundo)
red     = "#c34043"     # Vermelho terracota
green   = "#76946a"     # Verde musgo suave
yellow  = "#c0a36e"     # Amarelo areia
blue    = "#7e9cd8"     # Azul oceânico
magenta = "#957fb8"     # Roxo lavanda
cyan    = "#6a9589"     # Verde-água suave
white   = "#dcd7ba"     # Bege claro (texto principal)

# Cores brilhantes
[colors.bright]
black   = "#54546d"     # Cinza escuro para contrastes
red     = "#e82424"     # Vermelho vibrante
green   = "#98bb6c"     # Verde limão
yellow  = "#e6c384"     # Amarelo claro
blue    = "#7fb4ca"     # Azul claro
magenta = "#938aa9"     # Roxo acinzentado
cyan    = "#7aa89f"     # Azul esverdeado
white   = "#dcd7ba"     # Bege claro (destaques)

# Seleção
[colors.selection]
text = "#c8c093"         # Texto selecionado
background = "#2d4f67"   # Fundo da seleção

